image:
  repository: serdardevops/devops-atolyesi-app
  tag: "latest"
  pullPolicy: Always

replicaCount: 2

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30091

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

env:
  SPRING_PROFILES_ACTIVE: "docker"
  JAVA_OPTS: "-Xms128m -Xmx256m"

probes:
  liveness:
    initialDelaySeconds: 90
    periodSeconds: 30
    timeoutSeconds: 10
  readiness:
    initialDelaySeconds: 60
    periodSeconds: 15
    timeoutSeconds: 5 